---
- name: Copy the postgres_exporter systemd service file
  template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart postgres_exporter

- block:
    - name: Create postgres_exporter config directory
      file:
        path: "/etc/postgres_exporter"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy the postgres_exporter query file
      copy:
        src: queries.yml
        dest: /etc/postgres_exporter/queries.yml
        owner: root
        group: root
        mode: 0644
      notify: restart postgres_exporter
  when: postgres_exporter_extend_query_path | length > 0
