---
- import_tasks: preflight.yml
  tags:
    - postgres_exporter_install
    - postgres_exporter_configure
    - postgres_exporter_run

- import_tasks: install.yml
  become: true
  when:
    ( not __postgres_exporter_is_installed.stat.exists ) or
    ( (__postgres_exporter_current_version_output.stderr_lines | length > 0) and (__postgres_exporter_current_version_output.stderr_lines[0].split(" ")[2] != postgres_exporter_version) ) or
    ( (__postgres_exporter_current_version_output.stdout_lines | length > 0) and (__postgres_exporter_current_version_output.stdout_lines[0].split(" ")[2] != postgres_exporter_version) ) or
    ( postgres_exporter_binary_local_dir | length > 0 )
  tags:
    - postgres_exporter_install

- import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"
  tags:
    - postgres_exporter_configure

- import_tasks: configure.yml
  become: true
  tags:
    - postgres_exporter_configure

- name: Ensure Postgres Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: postgres_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - postgres_exporter_run
